# Generated by Django 4.0.3 on 2024-11-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0006_rename_user_type_profile_organization_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='template_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
